# Generated by Django 6.0.3 on 2026-03-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='LowCategorie',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='api.categorie')),
            ],
            options={
                'db_table': 'sous_categories',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('qte', models.IntegerField()),
                ('statut', models.CharField(max_length=64)),
                ('localisation', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='uploads/annonces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sous_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='api.lowcategorie')),
            ],
            options={
                'db_table': 'annonces',
            },
        ),
        migrations.AddConstraint(
            model_name='lowcategorie',
            constraint=models.UniqueConstraint(fields=('nom', 'categorie'), name='unique_sous_categorie_par_categorie'),
        ),
    ]
