# Generated by Django 6.0.3 on 2026-03-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_categorie_lowcategorie_annonce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnonce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/annonces/')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.annonce')),
            ],
        ),
    ]
