# Generated by Django 6.0.3 on 2026-03-16 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='vendeur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='api.users'),
            preserve_default=False,
        ),
    ]
