# Generated by Django 6.0.3 on 2026-03-25 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_annonce_vendeur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('idLivreur', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('numero_permis', models.CharField(blank=True, max_length=50, null=True)),
                ('type_vehicule', models.CharField(choices=[('moto', 'Moto'), ('voiture', 'Voiture'), ('velo', 'Vélo'), ('camion', 'Camion')], max_length=20)),
                ('plaque_immatriculation', models.CharField(blank=True, max_length=20, null=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('offline', 'Hors ligne')], default='offline', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur', to='api.users')),
            ],
            options={
                'db_table': 'livreurs',
            },
        ),
    ]
