# Generated by Django 6.0.3 on 2026-04-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_annonce_options_livreur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prix_total', models.IntegerField()),
                ('statut', models.CharField(default='En attente', max_length=64)),
                ('mode_paiement', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='api.users')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='api.annonce')),
            ],
            options={
                'db_table': 'ventes',
            },
        ),
    ]
