# Generated by Django 6.0.3 on 2026-04-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='annonce',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='quantite',
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.IntegerField()),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_vente', to='api.annonce')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.vente')),
            ],
            options={
                'db_table': 'lignes_vente',
            },
        ),
    ]
