# Generated by Django 6.0.3 on 2026-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_vente_annonce_remove_vente_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignevente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
