# Generated by Django 6.0.3 on 2026-04-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_lignevente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='code',
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
    ]
