# Generated by Django 6.0.3 on 2026-04-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_vente_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='prix_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
