# Generated by Django 6.0.3 on 2026-07-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_orderitems_panier_panieritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profils/'),
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='api.annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='api.users')),
            ],
            options={
                'db_table': 'favoris',
                'constraints': [models.UniqueConstraint(fields=('user', 'annonce'), name='unique_favoris')],
            },
        ),
    ]
