# Generated by Django 6.0.3 on 2026-07-09 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_users_photo_profil_favoris'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livreur',
            old_name='idLivreur',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='numero_permis',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='plaque_immatriculation',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='type_vehicule',
        ),
        migrations.AddField(
            model_name='order',
            name='statut_paiement',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('paye', 'Payé'), ('rembourse', 'Rembourse')], default='non_paye', max_length=20),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_livreur', to='api.users'),
        ),
        migrations.AlterModelTable(
            name='livreur',
            table=None,
        ),
        migrations.CreateModel(
            name='TrajetLivreur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='api.livreur')),
            ],
        ),
    ]
