# Generated by Django 6.0.3 on 2026-07-11 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_idlivreur_livreur_id_remove_livreur_actif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('paiement', 'Paiement'), ('remboursement', 'Remboursement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operateur', models.CharField(blank=True, max_length=20)),
                ('numero_telephone', models.CharField(blank=True, max_length=20)),
                ('cinetpay_transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_token', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.order')),
            ],
        ),
    ]
