# Generated by Django 6.0.3 on 2026-07-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='description_boutique',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='nom_boutique',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
