# Generated by Django 6.0.3 on 2026-07-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_users_description_boutique_users_nom_boutique'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trajetlivreur',
            name='tarif',
            field=models.IntegerField(default=0),
        ),
    ]
