# Generated by Django 6.0.3 on 2026-07-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_livreur_disponible_trajetlivreur_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livreur',
            name='num_permis',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='num_plaque',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='type_vehicule',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
