# Generated by Django 6.0.3 on 2026-07-24 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_livreur_is_validated_livreur_num_permis_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='panieritem',
            unique_together={('panier', 'annonce')},
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_livraison', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('en_attente_selection', 'En attente sélection livreur'), ('en_attente_acceptation', 'EN attente acceptation livreur'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('en_cours', 'En cours de livraison'), ('livree_attente_confirmation', 'Livrée - attente confirmation client'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente_selection', max_length=30)),
                ('date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.livreur')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='api.order')),
            ],
            options={
                'db_table': 'livraisons',
            },
        ),
    ]
