# Generated by Django 6.0.3 on 2026-07-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_panieritem_unique_together_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='is_validated',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('consulted_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.annonce')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users')),
            ],
            options={
                'db_table': 'consultations',
                'ordering': ['-consulted_at'],
            },
        ),
    ]
